# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1293, 848)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1265, 726))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 5, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_2.setMinimumSize(QtCore.QSize(100, 0))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 0, 7, 1, 1)
        self.label_found = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_found.setText("")
        self.label_found.setObjectName("label_found")
        self.gridLayout.addWidget(self.label_found, 6, 2, 1, 1)
        self.dest_dir = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.dest_dir.setObjectName("dest_dir")
        self.gridLayout.addWidget(self.dest_dir, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(13)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        self.gridLayout.addWidget(self.tableWidget, 7, 0, 1, 8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.find_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.find_button.setObjectName("find_button")
        self.horizontalLayout.addWidget(self.find_button)
        self.analyze_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.analyze_button.setObjectName("analyze_button")
        self.horizontalLayout.addWidget(self.analyze_button)
        self.users_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.users_button.setObjectName("users_button")
        self.horizontalLayout.addWidget(self.users_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 8)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        self.chooseDir = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.chooseDir.setObjectName("chooseDir")
        self.gridLayout.addWidget(self.chooseDir, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.del_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.del_button.setObjectName("del_button")
        self.horizontalLayout_2.addWidget(self.del_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.stop_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_3.addWidget(self.stop_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 2, 1, 5)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_server = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_server.setFont(font)
        self.label_server.setObjectName("label_server")
        self.gridLayout_3.addWidget(self.label_server, 7, 1, 1, 1)
        self.label_port = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_port.setFont(font)
        self.label_port.setObjectName("label_port")
        self.gridLayout_3.addWidget(self.label_port, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 8, 0, 1, 1)
        self.label_user = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        self.gridLayout_3.addWidget(self.label_user, 9, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("icons/if_Circle_Red_34214.ico"))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.label_status = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_6.addWidget(self.label_status)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.button_connect = QtWidgets.QPushButton(self.groupBox)
        self.button_connect.setObjectName("button_connect")
        self.horizontalLayout_8.addWidget(self.button_connect)
        self.button_login = QtWidgets.QPushButton(self.groupBox)
        self.button_login.setObjectName("button_login")
        self.horizontalLayout_8.addWidget(self.button_login)
        self.button_logout = QtWidgets.QPushButton(self.groupBox)
        self.button_logout.setObjectName("button_logout")
        self.horizontalLayout_8.addWidget(self.button_logout)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 2)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_from = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_from.setFont(font)
        self.label_from.setObjectName("label_from")
        self.gridLayout_2.addWidget(self.label_from, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_topic = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_topic.setFont(font)
        self.label_topic.setObjectName("label_topic")
        self.gridLayout_2.addWidget(self.label_topic, 2, 1, 1, 3)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_text = QtWidgets.QLabel(self.groupBox_2)
        self.label_text.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_text.setFont(font)
        self.label_text.setObjectName("label_text")
        self.gridLayout_2.addWidget(self.label_text, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_ans = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ans.setFont(font)
        self.label_ans.setObjectName("label_ans")
        self.gridLayout_2.addWidget(self.label_ans, 1, 1, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.tableWidget_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 2, 1, 1)
        self.date_from = QtWidgets.QDateEdit(self.page_3)
        self.date_from.setObjectName("date_from")
        self.gridLayout_4.addWidget(self.date_from, 2, 3, 1, 1)
        self.query = QtWidgets.QLineEdit(self.page_3)
        self.query.setObjectName("query")
        self.gridLayout_4.addWidget(self.query, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 4, 1, 1)
        self.date_to = QtWidgets.QDateEdit(self.page_3)
        self.date_to.setObjectName("date_to")
        self.gridLayout_4.addWidget(self.date_to, 2, 5, 1, 1)
        self.find = QtWidgets.QPushButton(self.page_3)
        self.find.setObjectName("find")
        self.gridLayout_4.addWidget(self.find, 2, 6, 1, 1)
        self.read_log = QtWidgets.QPushButton(self.page_3)
        self.read_log.setObjectName("read_log")
        self.gridLayout_4.addWidget(self.read_log, 0, 6, 1, 1)
        self.choose_log = QtWidgets.QPushButton(self.page_3)
        self.choose_log.setObjectName("choose_log")
        self.gridLayout_4.addWidget(self.choose_log, 0, 5, 1, 1)
        self.logpath = QtWidgets.QLineEdit(self.page_3)
        self.logpath.setObjectName("logpath")
        self.gridLayout_4.addWidget(self.logpath, 0, 1, 1, 4)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.verticalLayout_5.addWidget(self.tableWidget_3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_20 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 2, 2, 1, 1)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.page_4)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.gridLayout_5.addWidget(self.dateEdit_3, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.page_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 3)
        self.label_21 = QtWidgets.QLabel(self.page_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 2, 0, 1, 1)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.page_4)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.gridLayout_5.addWidget(self.dateEdit_4, 2, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 1, 1, 3)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 0, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.treeWidget = QtWidgets.QTreeWidget(self.page_4)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_6.addWidget(self.treeWidget)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.raport_button = QtWidgets.QPushButton(self.page_4)
        self.raport_button.setMinimumSize(QtCore.QSize(200, 0))
        self.raport_button.setObjectName("raport_button")
        self.horizontalLayout_10.addWidget(self.raport_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1293, 33))
        self.menubar.setObjectName("menubar")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        self.menuEksportuj = QtWidgets.QMenu(self.menuPlik)
        self.menuEksportuj.setObjectName("menuEksportuj")
        self.menuOpcje = QtWidgets.QMenu(self.menubar)
        self.menuOpcje.setObjectName("menuOpcje")
        self.menuServer_connection = QtWidgets.QMenu(self.menubar)
        self.menuServer_connection.setObjectName("menuServer_connection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDo_CSV = QtWidgets.QAction(MainWindow)
        self.actionDo_CSV.setObjectName("actionDo_CSV")
        self.actionDo_XLS = QtWidgets.QAction(MainWindow)
        self.actionDo_XLS.setObjectName("actionDo_XLS")
        self.actionImportuj = QtWidgets.QAction(MainWindow)
        self.actionImportuj.setObjectName("actionImportuj")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionUsers = QtWidgets.QAction(MainWindow)
        self.actionUsers.setObjectName("actionUsers")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionClose_connection = QtWidgets.QAction(MainWindow)
        self.actionClose_connection.setObjectName("actionClose_connection")
        self.actionSend_mail = QtWidgets.QAction(MainWindow)
        self.actionSend_mail.setObjectName("actionSend_mail")
        self.actionPayments = QtWidgets.QAction(MainWindow)
        self.actionPayments.setObjectName("actionPayments")
        self.actionLogs = QtWidgets.QAction(MainWindow)
        self.actionLogs.setObjectName("actionLogs")
        self.actionOpen_log = QtWidgets.QAction(MainWindow)
        self.actionOpen_log.setObjectName("actionOpen_log")
        self.menuEksportuj.addAction(self.actionDo_CSV)
        self.menuEksportuj.addAction(self.actionDo_XLS)
        self.menuPlik.addAction(self.actionSend_mail)
        self.menuPlik.addAction(self.actionPayments)
        self.menuPlik.addAction(self.actionLogs)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.menuEksportuj.menuAction())
        self.menuPlik.addAction(self.actionImportuj)
        self.menuPlik.addAction(self.actionOpen_log)
        self.menuOpcje.addAction(self.actionUsers)
        self.menuOpcje.addAction(self.actionPreferences)
        self.menuServer_connection.addAction(self.actionConnect)
        self.menuServer_connection.addAction(self.actionLogin)
        self.menuServer_connection.addAction(self.actionClose_connection)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuServer_connection.menuAction())
        self.menubar.addAction(self.menuOpcje.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rozliczenie NMR"))
        self.label_2.setText(_translate("MainWindow", "Od:"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nazwa widma"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nazwa użytkownika"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Użytkownik"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Płatnik"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Koniec"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Czas"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Czas [s]"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "EXP"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "NS"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "TD1"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "TD2"))
        self.find_button.setText(_translate("MainWindow", "Znajdź widma"))
        self.analyze_button.setText(_translate("MainWindow", "Wczytaj pliki"))
        self.users_button.setText(_translate("MainWindow", "Dopasuj użytkowników"))
        self.label_3.setText(_translate("MainWindow", "do:"))
        self.chooseDir.setText(_translate("MainWindow", "Folder"))
        self.label.setText(_translate("MainWindow", "Podsumowanie:"))
        self.label_22.setText(_translate("MainWindow", "Cena za 1h:"))
        self.pushButton.setText(_translate("MainWindow", "Wyświetl podsumowanie"))
        self.del_button.setText(_translate("MainWindow", "Usuń wiersze"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.label_4.setText(_translate("MainWindow", "Mail module"))
        self.groupBox.setTitle(_translate("MainWindow", "Ser&ver settings"))
        self.label_15.setText(_translate("MainWindow", "Status:"))
        self.label_server.setText(_translate("MainWindow", "mail.ch.uj.edu.pl"))
        self.label_port.setText(_translate("MainWindow", "25"))
        self.label_13.setText(_translate("MainWindow", "User:"))
        self.label_11.setText(_translate("MainWindow", "Port:"))
        self.label_user.setText(_translate("MainWindow", "pustulam"))
        self.label_5.setText(_translate("MainWindow", "SMTP server:"))
        self.label_status.setText(_translate("MainWindow", "No connection"))
        self.button_connect.setText(_translate("MainWindow", "Connect"))
        self.button_login.setText(_translate("MainWindow", "Log in"))
        self.button_logout.setText(_translate("MainWindow", "Close connection"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Message settings"))
        self.label_7.setText(_translate("MainWindow", "From:"))
        self.label_from.setText(_translate("MainWindow", "nmr@chemia.uj.edu.pl"))
        self.label_12.setText(_translate("MainWindow", "Topic:"))
        self.label_topic.setText(_translate("MainWindow", "topic"))
        self.label_16.setText(_translate("MainWindow", "Message text:"))
        self.label_text.setText(_translate("MainWindow", "message"))
        self.label_9.setText(_translate("MainWindow", "Answer to:"))
        self.label_ans.setText(_translate("MainWindow", "nmr@chemia.uj.edu.pl"))
        self.pushButton_2.setText(_translate("MainWindow", "Add spectrum folder"))
        self.pushButton_3.setText(_translate("MainWindow", "Match users"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Spectrum"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mail"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total size"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        self.pushButton_5.setText(_translate("MainWindow", "Send all"))
        self.pushButton_6.setText(_translate("MainWindow", "Send selected"))
        self.pushButton_7.setText(_translate("MainWindow", "Abort sending"))
        self.label_6.setText(_translate("MainWindow", "Log file:"))
        self.label_14.setText(_translate("MainWindow", "Find:"))
        self.label_10.setText(_translate("MainWindow", "Beetween dates:"))
        self.label_18.setText(_translate("MainWindow", "and"))
        self.find.setText(_translate("MainWindow", "Find"))
        self.read_log.setText(_translate("MainWindow", "Read"))
        self.choose_log.setText(_translate("MainWindow", "Choose"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sent to"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        self.label_20.setText(_translate("MainWindow", "do:"))
        self.label_19.setText(_translate("MainWindow", "Rodzaj zlecenia:"))
        self.label_8.setText(_translate("MainWindow", "Podsumowanie"))
        self.label_21.setText(_translate("MainWindow", "Okres:"))
        self.pushButton_8.setText(_translate("MainWindow", "Wstecz"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Płatnik"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Liczba widm"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Czas"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Czas [s]"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Koszt"))
        self.raport_button.setText(_translate("MainWindow", "Utwórz raport"))
        self.menuPlik.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuEksportuj.setTitle(_translate("MainWindow", "&Export"))
        self.menuOpcje.setTitle(_translate("MainWindow", "Optio&ns"))
        self.menuServer_connection.setTitle(_translate("MainWindow", "Ser&ver connection"))
        self.actionDo_CSV.setText(_translate("MainWindow", "&to CSV"))
        self.actionDo_XLS.setText(_translate("MainWindow", "to &XLS"))
        self.actionImportuj.setText(_translate("MainWindow", "&Import"))
        self.actionPreferences.setText(_translate("MainWindow", "&Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "F9"))
        self.actionUsers.setText(_translate("MainWindow", "&Users"))
        self.actionUsers.setShortcut(_translate("MainWindow", "F5"))
        self.actionConnect.setText(_translate("MainWindow", "&Connect"))
        self.actionConnect.setShortcut(_translate("MainWindow", "F1"))
        self.actionLogin.setText(_translate("MainWindow", "&Login"))
        self.actionLogin.setShortcut(_translate("MainWindow", "F2"))
        self.actionClose_connection.setText(_translate("MainWindow", "Cl&ose connection"))
        self.actionClose_connection.setShortcut(_translate("MainWindow", "F4"))
        self.actionSend_mail.setText(_translate("MainWindow", "&Send mails"))
        self.actionPayments.setText(_translate("MainWindow", "&Payments"))
        self.actionLogs.setText(_translate("MainWindow", "&Logs"))
        self.actionOpen_log.setText(_translate("MainWindow", "&Open log"))
        self.actionOpen_log.setShortcut(_translate("MainWindow", "Ctrl+O"))

