# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1350, 895)
        font = QtGui.QFont()
        font.setFamily("Oxygen-Sans")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 618, 293))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit.setMinimumSize(QtCore.QSize(100, 0))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 5, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateEdit_2.setMinimumSize(QtCore.QSize(100, 0))
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout.addWidget(self.dateEdit_2, 0, 7, 1, 1)
        self.label_found = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_found.setText("")
        self.label_found.setObjectName("label_found")
        self.gridLayout.addWidget(self.label_found, 6, 2, 1, 1)
        self.dest_dir = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.dest_dir.setObjectName("dest_dir")
        self.gridLayout.addWidget(self.dest_dir, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(13)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        self.gridLayout.addWidget(self.tableWidget, 7, 0, 1, 8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.find_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.find_button.setObjectName("find_button")
        self.horizontalLayout.addWidget(self.find_button)
        self.analyze_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.analyze_button.setObjectName("analyze_button")
        self.horizontalLayout.addWidget(self.analyze_button)
        self.users_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.users_button.setObjectName("users_button")
        self.horizontalLayout.addWidget(self.users_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 8)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        self.chooseDir = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.chooseDir.setObjectName("chooseDir")
        self.gridLayout.addWidget(self.chooseDir, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.del_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.del_button.setObjectName("del_button")
        self.horizontalLayout_2.addWidget(self.del_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.stop_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_3.addWidget(self.stop_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 2, 1, 5)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_server = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_server.setFont(font)
        self.label_server.setObjectName("label_server")
        self.gridLayout_3.addWidget(self.label_server, 7, 1, 1, 1)
        self.label_port = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_port.setFont(font)
        self.label_port.setObjectName("label_port")
        self.gridLayout_3.addWidget(self.label_port, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 8, 0, 1, 1)
        self.label_user = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        self.gridLayout_3.addWidget(self.label_user, 9, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 7, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("icons/if_Circle_Red_34214.ico"))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.label_status = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.horizontalLayout_6.addWidget(self.label_status)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.button_connect = QtWidgets.QPushButton(self.groupBox)
        self.button_connect.setObjectName("button_connect")
        self.horizontalLayout_8.addWidget(self.button_connect)
        self.button_login = QtWidgets.QPushButton(self.groupBox)
        self.button_login.setObjectName("button_login")
        self.horizontalLayout_8.addWidget(self.button_login)
        self.button_logout = QtWidgets.QPushButton(self.groupBox)
        self.button_logout.setObjectName("button_logout")
        self.horizontalLayout_8.addWidget(self.button_logout)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 2)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_from = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_from.setFont(font)
        self.label_from.setObjectName("label_from")
        self.gridLayout_2.addWidget(self.label_from, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_topic = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_topic.setFont(font)
        self.label_topic.setObjectName("label_topic")
        self.gridLayout_2.addWidget(self.label_topic, 2, 1, 1, 3)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_text = QtWidgets.QLabel(self.groupBox_2)
        self.label_text.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_text.setFont(font)
        self.label_text.setObjectName("label_text")
        self.gridLayout_2.addWidget(self.label_text, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_ans = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_ans.setFont(font)
        self.label_ans.setObjectName("label_ans")
        self.gridLayout_2.addWidget(self.label_ans, 1, 1, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.tableWidget_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 2, 1, 1)
        self.date_from = QtWidgets.QDateEdit(self.page_3)
        self.date_from.setObjectName("date_from")
        self.gridLayout_4.addWidget(self.date_from, 2, 3, 1, 1)
        self.query = QtWidgets.QLineEdit(self.page_3)
        self.query.setObjectName("query")
        self.gridLayout_4.addWidget(self.query, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 4, 1, 1)
        self.date_to = QtWidgets.QDateEdit(self.page_3)
        self.date_to.setObjectName("date_to")
        self.gridLayout_4.addWidget(self.date_to, 2, 5, 1, 1)
        self.find = QtWidgets.QPushButton(self.page_3)
        self.find.setObjectName("find")
        self.gridLayout_4.addWidget(self.find, 2, 6, 1, 1)
        self.read_log = QtWidgets.QPushButton(self.page_3)
        self.read_log.setObjectName("read_log")
        self.gridLayout_4.addWidget(self.read_log, 0, 6, 1, 1)
        self.choose_log = QtWidgets.QPushButton(self.page_3)
        self.choose_log.setObjectName("choose_log")
        self.gridLayout_4.addWidget(self.choose_log, 0, 5, 1, 1)
        self.logpath = QtWidgets.QLineEdit(self.page_3)
        self.logpath.setObjectName("logpath")
        self.gridLayout_4.addWidget(self.logpath, 0, 1, 1, 4)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.verticalLayout_5.addWidget(self.tableWidget_3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_20 = QtWidgets.QLabel(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 3, 2, 1, 1)
        self.dateEdit_3 = QtWidgets.QDateEdit(self.page_4)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.gridLayout_5.addWidget(self.dateEdit_3, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 3)
        self.label_21 = QtWidgets.QLabel(self.page_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 3, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 1, 1, 1, 3)
        self.dateEdit_4 = QtWidgets.QDateEdit(self.page_4)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.gridLayout_5.addWidget(self.dateEdit_4, 3, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 0, 3, 1, 1)
        self.Combo_Zlec = QtWidgets.QComboBox(self.page_4)
        self.Combo_Zlec.setEditable(True)
        self.Combo_Zlec.setObjectName("Combo_Zlec")
        self.gridLayout_5.addWidget(self.Combo_Zlec, 2, 1, 1, 3)
        self.label_19 = QtWidgets.QLabel(self.page_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.page_4)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.treeWidget = QtWidgets.QTreeWidget(self.page_4)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_6.addWidget(self.treeWidget)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.raport_button = QtWidgets.QPushButton(self.page_4)
        self.raport_button.setMinimumSize(QtCore.QSize(200, 0))
        self.raport_button.setObjectName("raport_button")
        self.horizontalLayout_10.addWidget(self.raport_button)
        self.label_39 = QtWidgets.QLabel(self.page_4)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_10.addWidget(self.label_39)
        self.raport_path = QtWidgets.QLineEdit(self.page_4)
        self.raport_path.setObjectName("raport_path")
        self.horizontalLayout_10.addWidget(self.raport_path)
        self.zaksieguj = QtWidgets.QPushButton(self.page_4)
        self.zaksieguj.setMinimumSize(QtCore.QSize(200, 0))
        self.zaksieguj.setObjectName("zaksieguj")
        self.horizontalLayout_10.addWidget(self.zaksieguj)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.new_bill = QtWidgets.QPushButton(self.page_5)
        self.new_bill.setObjectName("new_bill")
        self.gridLayout_8.addWidget(self.new_bill, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 0, 0, 1, 1)
        self.edit_bill = QtWidgets.QPushButton(self.page_5)
        self.edit_bill.setObjectName("edit_bill")
        self.gridLayout_8.addWidget(self.edit_bill, 0, 2, 1, 1)
        self.delete_bill = QtWidgets.QPushButton(self.page_5)
        self.delete_bill.setObjectName("delete_bill")
        self.gridLayout_8.addWidget(self.delete_bill, 0, 4, 1, 1)
        self.archive_button = QtWidgets.QPushButton(self.page_5)
        self.archive_button.setObjectName("archive_button")
        self.gridLayout_8.addWidget(self.archive_button, 0, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_8)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.created_to = QtWidgets.QDateEdit(self.page_5)
        self.created_to.setObjectName("created_to")
        self.gridLayout_6.addWidget(self.created_to, 1, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.page_5)
        self.line.setMinimumSize(QtCore.QSize(20, 0))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 0, 4, 2, 1)
        self.filter_bills = QtWidgets.QPushButton(self.page_5)
        self.filter_bills.setObjectName("filter_bills")
        self.gridLayout_6.addWidget(self.filter_bills, 2, 7, 1, 2)
        self.bill_payer = QtWidgets.QComboBox(self.page_5)
        self.bill_payer.setEnabled(True)
        self.bill_payer.setEditable(True)
        self.bill_payer.setObjectName("bill_payer")
        self.gridLayout_6.addWidget(self.bill_payer, 0, 6, 1, 3)
        self.created_from = QtWidgets.QDateEdit(self.page_5)
        self.created_from.setObjectName("created_from")
        self.gridLayout_6.addWidget(self.created_from, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.page_5)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.page_5)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(60, 0))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.page_5)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 1, 5, 1, 1)
        self.exp_from = QtWidgets.QDateEdit(self.page_5)
        self.exp_from.setObjectName("exp_from")
        self.gridLayout_6.addWidget(self.exp_from, 1, 6, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(60, 0))
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 1, 7, 1, 1)
        self.expt_to = QtWidgets.QDateEdit(self.page_5)
        self.expt_to.setObjectName("expt_to")
        self.gridLayout_6.addWidget(self.expt_to, 1, 8, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_5)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 5, 1, 1)
        self.type_exp = QtWidgets.QComboBox(self.page_5)
        self.type_exp.setEditable(True)
        self.type_exp.setObjectName("type_exp")
        self.gridLayout_6.addWidget(self.type_exp, 0, 1, 1, 3)
        self.line_3 = QtWidgets.QFrame(self.page_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_6.addWidget(self.line_3, 3, 0, 1, 9)
        self.check_uznania = QtWidgets.QCheckBox(self.page_5)
        self.check_uznania.setChecked(True)
        self.check_uznania.setObjectName("check_uznania")
        self.gridLayout_6.addWidget(self.check_uznania, 2, 6, 1, 1)
        self.check_obciazenia = QtWidgets.QCheckBox(self.page_5)
        self.check_obciazenia.setChecked(True)
        self.check_obciazenia.setObjectName("check_obciazenia")
        self.gridLayout_6.addWidget(self.check_obciazenia, 2, 5, 1, 1)
        self.check_arch = QtWidgets.QCheckBox(self.page_5)
        self.check_arch.setObjectName("check_arch")
        self.gridLayout_6.addWidget(self.check_arch, 2, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_6)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.bill_price = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bill_price.sizePolicy().hasHeightForWidth())
        self.bill_price.setSizePolicy(sizePolicy)
        self.bill_price.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bill_price.setFont(font)
        self.bill_price.setTextFormat(QtCore.Qt.AutoText)
        self.bill_price.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bill_price.setObjectName("bill_price")
        self.gridLayout_7.addWidget(self.bill_price, 1, 7, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.page_5)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 1, 6, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.page_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 1, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.page_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.page_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.page_5)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 1, 4, 1, 1)
        self.num_bills = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.num_bills.setFont(font)
        self.num_bills.setObjectName("num_bills")
        self.gridLayout_7.addWidget(self.num_bills, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_7.addWidget(self.label_42, 2, 4, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 3, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 2, 2, 1, 1)
        self.bill_num_exp_o = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bill_num_exp_o.setFont(font)
        self.bill_num_exp_o.setObjectName("bill_num_exp_o")
        self.gridLayout_7.addWidget(self.bill_num_exp_o, 3, 3, 1, 1)
        self.bill_price_w = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bill_price_w.sizePolicy().hasHeightForWidth())
        self.bill_price_w.setSizePolicy(sizePolicy)
        self.bill_price_w.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bill_price_w.setFont(font)
        self.bill_price_w.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bill_price_w.setObjectName("bill_price_w")
        self.gridLayout_7.addWidget(self.bill_price_w, 2, 7, 1, 1)
        self.bill_time_exp_o = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bill_time_exp_o.setFont(font)
        self.bill_time_exp_o.setObjectName("bill_time_exp_o")
        self.gridLayout_7.addWidget(self.bill_time_exp_o, 3, 5, 1, 1)
        self.bill_price_o = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bill_price_o.sizePolicy().hasHeightForWidth())
        self.bill_price_o.setSizePolicy(sizePolicy)
        self.bill_price_o.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bill_price_o.setFont(font)
        self.bill_price_o.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bill_price_o.setObjectName("bill_price_o")
        self.gridLayout_7.addWidget(self.bill_price_o, 3, 7, 1, 1)
        self.bill_time_exp_w = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bill_time_exp_w.setFont(font)
        self.bill_time_exp_w.setObjectName("bill_time_exp_w")
        self.gridLayout_7.addWidget(self.bill_time_exp_w, 2, 5, 1, 1)
        self.bill_time_exp = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bill_time_exp.setFont(font)
        self.bill_time_exp.setObjectName("bill_time_exp")
        self.gridLayout_7.addWidget(self.bill_time_exp, 1, 5, 1, 1)
        self.bill_num_exp = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bill_num_exp.setFont(font)
        self.bill_num_exp.setObjectName("bill_num_exp")
        self.gridLayout_7.addWidget(self.bill_num_exp, 1, 3, 1, 1)
        self.bill_num_exp_w = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bill_num_exp_w.setFont(font)
        self.bill_num_exp_w.setObjectName("bill_num_exp_w")
        self.gridLayout_7.addWidget(self.bill_num_exp_w, 2, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 2, 0, 1, 1)
        self.num_bills_w = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.num_bills_w.setFont(font)
        self.num_bills_w.setObjectName("num_bills_w")
        self.gridLayout_7.addWidget(self.num_bills_w, 2, 1, 1, 1)
        self.num_bills_o = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.num_bills_o.setFont(font)
        self.num_bills_o.setObjectName("num_bills_o")
        self.gridLayout_7.addWidget(self.num_bills_o, 3, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 3, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_7.addWidget(self.label_43, 3, 4, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_7.addWidget(self.label_44, 2, 6, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_7.addWidget(self.label_45, 3, 6, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.page_5)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 1, 8, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_7)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_46 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setObjectName("label_46")
        self.gridLayout_9.addWidget(self.label_46, 0, 0, 1, 1)
        self.platnik_send = QtWidgets.QComboBox(self.page_5)
        self.platnik_send.setObjectName("platnik_send")
        self.gridLayout_9.addWidget(self.platnik_send, 0, 1, 1, 1)
        self.send_bill_msg = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_bill_msg.sizePolicy().hasHeightForWidth())
        self.send_bill_msg.setSizePolicy(sizePolicy)
        self.send_bill_msg.setObjectName("send_bill_msg")
        self.gridLayout_9.addWidget(self.send_bill_msg, 0, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_9)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.page_5)
        self.tableWidget_4.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_4.setAlternatingRowColors(True)
        self.tableWidget_4.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(13)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(12, item)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_4.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tableWidget_4)
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1350, 33))
        self.menubar.setObjectName("menubar")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        self.menuEksportuj = QtWidgets.QMenu(self.menuPlik)
        self.menuEksportuj.setObjectName("menuEksportuj")
        self.menuOpcje = QtWidgets.QMenu(self.menubar)
        self.menuOpcje.setObjectName("menuOpcje")
        self.menuServer_connection = QtWidgets.QMenu(self.menubar)
        self.menuServer_connection.setObjectName("menuServer_connection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDo_CSV = QtWidgets.QAction(MainWindow)
        self.actionDo_CSV.setObjectName("actionDo_CSV")
        self.actionDo_XLS = QtWidgets.QAction(MainWindow)
        self.actionDo_XLS.setObjectName("actionDo_XLS")
        self.actionImportuj = QtWidgets.QAction(MainWindow)
        self.actionImportuj.setObjectName("actionImportuj")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionUsers = QtWidgets.QAction(MainWindow)
        self.actionUsers.setObjectName("actionUsers")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionClose_connection = QtWidgets.QAction(MainWindow)
        self.actionClose_connection.setObjectName("actionClose_connection")
        self.actionSend_mail = QtWidgets.QAction(MainWindow)
        self.actionSend_mail.setObjectName("actionSend_mail")
        self.actionPayments = QtWidgets.QAction(MainWindow)
        self.actionPayments.setObjectName("actionPayments")
        self.actionLogs = QtWidgets.QAction(MainWindow)
        self.actionLogs.setObjectName("actionLogs")
        self.actionOpen_log = QtWidgets.QAction(MainWindow)
        self.actionOpen_log.setObjectName("actionOpen_log")
        self.actionBills = QtWidgets.QAction(MainWindow)
        self.actionBills.setObjectName("actionBills")
        self.menuEksportuj.addAction(self.actionDo_CSV)
        self.menuEksportuj.addAction(self.actionDo_XLS)
        self.menuPlik.addAction(self.actionSend_mail)
        self.menuPlik.addAction(self.actionPayments)
        self.menuPlik.addAction(self.actionBills)
        self.menuPlik.addAction(self.actionLogs)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.menuEksportuj.menuAction())
        self.menuPlik.addAction(self.actionImportuj)
        self.menuPlik.addAction(self.actionOpen_log)
        self.menuOpcje.addAction(self.actionUsers)
        self.menuOpcje.addAction(self.actionPreferences)
        self.menuServer_connection.addAction(self.actionConnect)
        self.menuServer_connection.addAction(self.actionLogin)
        self.menuServer_connection.addAction(self.actionClose_connection)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuServer_connection.menuAction())
        self.menubar.addAction(self.menuOpcje.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rozliczenie NMR"))
        self.label_2.setText(_translate("MainWindow", "Od:"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nazwa widma"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nazwa użytkownika"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Użytkownik"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Płatnik"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Koniec"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Czas"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Czas [s]"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "EXP"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "NS"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "TD1"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "TD2"))
        self.find_button.setText(_translate("MainWindow", "Znajdź widma"))
        self.analyze_button.setText(_translate("MainWindow", "Wczytaj pliki"))
        self.users_button.setText(_translate("MainWindow", "Dopasuj użytkowników"))
        self.label_3.setText(_translate("MainWindow", "do:"))
        self.chooseDir.setText(_translate("MainWindow", "Folder"))
        self.label.setText(_translate("MainWindow", "Podsumowanie:"))
        self.label_22.setText(_translate("MainWindow", "Cena za 1h:"))
        self.pushButton.setText(_translate("MainWindow", "Wyświetl podsumowanie"))
        self.del_button.setText(_translate("MainWindow", "Usuń wiersze"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.label_4.setText(_translate("MainWindow", "Mail module"))
        self.groupBox.setTitle(_translate("MainWindow", "Ser&ver settings"))
        self.label_15.setText(_translate("MainWindow", "Status:"))
        self.label_server.setText(_translate("MainWindow", "mail.ch.uj.edu.pl"))
        self.label_port.setText(_translate("MainWindow", "25"))
        self.label_13.setText(_translate("MainWindow", "User:"))
        self.label_11.setText(_translate("MainWindow", "Port:"))
        self.label_user.setText(_translate("MainWindow", "pustulam"))
        self.label_5.setText(_translate("MainWindow", "SMTP server:"))
        self.label_status.setText(_translate("MainWindow", "No connection"))
        self.button_connect.setText(_translate("MainWindow", "Connect"))
        self.button_login.setText(_translate("MainWindow", "Log in"))
        self.button_logout.setText(_translate("MainWindow", "Close connection"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Message settings"))
        self.label_7.setText(_translate("MainWindow", "From:"))
        self.label_from.setText(_translate("MainWindow", "nmr@chemia.uj.edu.pl"))
        self.label_12.setText(_translate("MainWindow", "Topic:"))
        self.label_topic.setText(_translate("MainWindow", "topic"))
        self.label_16.setText(_translate("MainWindow", "Message text:"))
        self.label_text.setText(_translate("MainWindow", "message"))
        self.label_9.setText(_translate("MainWindow", "Answer to:"))
        self.label_ans.setText(_translate("MainWindow", "nmr@chemia.uj.edu.pl"))
        self.pushButton_2.setText(_translate("MainWindow", "Add spectrum folder"))
        self.pushButton_3.setText(_translate("MainWindow", "Match users"))
        self.pushButton_4.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Spectrum"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mail"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total size"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        self.pushButton_5.setText(_translate("MainWindow", "Send all"))
        self.pushButton_6.setText(_translate("MainWindow", "Send selected"))
        self.pushButton_7.setText(_translate("MainWindow", "Abort sending"))
        self.label_6.setText(_translate("MainWindow", "Log file:"))
        self.label_14.setText(_translate("MainWindow", "Find:"))
        self.label_10.setText(_translate("MainWindow", "Beetween dates:"))
        self.label_18.setText(_translate("MainWindow", "and"))
        self.find.setText(_translate("MainWindow", "Find"))
        self.read_log.setText(_translate("MainWindow", "Read"))
        self.choose_log.setText(_translate("MainWindow", "Choose"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sent to"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        self.label_20.setText(_translate("MainWindow", "do:"))
        self.label_8.setText(_translate("MainWindow", "Podsumowanie"))
        self.label_21.setText(_translate("MainWindow", "Okres:"))
        self.pushButton_8.setText(_translate("MainWindow", "Wstecz"))
        self.label_19.setText(_translate("MainWindow", "Rodzaj zlecenia:"))
        self.label_32.setText(_translate("MainWindow", "Katalog:"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Płatnik"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Liczba widm"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Czas"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Czas [s]"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Koszt"))
        self.raport_button.setText(_translate("MainWindow", "Utwórz raport"))
        self.label_39.setText(_translate("MainWindow", "Raport:"))
        self.zaksieguj.setText(_translate("MainWindow", "Zaksięguj"))
        self.new_bill.setText(_translate("MainWindow", "Nowy wpis"))
        self.label_23.setText(_translate("MainWindow", "Płatności i rozliczenia"))
        self.edit_bill.setText(_translate("MainWindow", "Edytuj wpis"))
        self.delete_bill.setText(_translate("MainWindow", "Usuń wpis"))
        self.delete_bill.setShortcut(_translate("MainWindow", "Del"))
        self.archive_button.setText(_translate("MainWindow", "Archiwizuj"))
        self.filter_bills.setText(_translate("MainWindow", "Filtruj"))
        self.label_24.setText(_translate("MainWindow", "Rodzaj zleceń:"))
        self.label_26.setText(_translate("MainWindow", "Wystawione od:"))
        self.label_27.setText(_translate("MainWindow", "do:"))
        self.label_28.setText(_translate("MainWindow", "Za okres od:"))
        self.label_29.setText(_translate("MainWindow", "do:"))
        self.label_25.setText(_translate("MainWindow", "Płatnik:"))
        self.check_uznania.setText(_translate("MainWindow", "Uznania"))
        self.check_obciazenia.setText(_translate("MainWindow", "Obciążenia"))
        self.check_arch.setText(_translate("MainWindow", "Archiwalne"))
        self.bill_price.setText(_translate("MainWindow", "500"))
        self.label_36.setText(_translate("MainWindow", "Saldo [PLN]:"))
        self.label_33.setText(_translate("MainWindow", "Całkowita liczba pomiarów:"))
        self.label_30.setText(_translate("MainWindow", "Podsumowanie:"))
        self.label_31.setText(_translate("MainWindow", "Liczba pozycji:"))
        self.label_35.setText(_translate("MainWindow", "Liczba godzin:"))
        self.num_bills.setText(_translate("MainWindow", "14"))
        self.label_42.setText(_translate("MainWindow", "zmierzone:"))
        self.label_38.setText(_translate("MainWindow", "Uznania:"))
        self.label_40.setText(_translate("MainWindow", "wykonane:"))
        self.bill_num_exp_o.setText(_translate("MainWindow", "541"))
        self.bill_price_w.setText(_translate("MainWindow", "500"))
        self.bill_time_exp_o.setText(_translate("MainWindow", "541"))
        self.bill_price_o.setText(_translate("MainWindow", "100"))
        self.bill_time_exp_w.setText(_translate("MainWindow", "541"))
        self.bill_time_exp.setText(_translate("MainWindow", "1166"))
        self.bill_num_exp.setText(_translate("MainWindow", "541"))
        self.bill_num_exp_w.setText(_translate("MainWindow", "541"))
        self.label_34.setText(_translate("MainWindow", "Obciążenia:"))
        self.num_bills_w.setText(_translate("MainWindow", "8"))
        self.num_bills_o.setText(_translate("MainWindow", "6"))
        self.label_41.setText(_translate("MainWindow", "opłacone:"))
        self.label_43.setText(_translate("MainWindow", "opłacone:"))
        self.label_44.setText(_translate("MainWindow", "Należności:"))
        self.label_45.setText(_translate("MainWindow", "Wpłaty:"))
        self.label_46.setText(_translate("MainWindow", "Powiadomienia o płatnościach"))
        self.send_bill_msg.setText(_translate("MainWindow", "Wyślij powiadomienie"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rodzaj wpisu"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Rodzaj zlecenia"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Płatnik"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Kwota"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Liczba godzin"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Liczba pomiarów"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Od"))
        item = self.tableWidget_4.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Do"))
        item = self.tableWidget_4.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Uwagi"))
        item = self.tableWidget_4.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Raport"))
        item = self.tableWidget_4.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Status"))
        self.menuPlik.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuEksportuj.setTitle(_translate("MainWindow", "&Export"))
        self.menuOpcje.setTitle(_translate("MainWindow", "Optio&ns"))
        self.menuServer_connection.setTitle(_translate("MainWindow", "Ser&ver connection"))
        self.actionDo_CSV.setText(_translate("MainWindow", "&to CSV"))
        self.actionDo_XLS.setText(_translate("MainWindow", "to &XLS"))
        self.actionImportuj.setText(_translate("MainWindow", "&Import"))
        self.actionPreferences.setText(_translate("MainWindow", "&Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "F9"))
        self.actionUsers.setText(_translate("MainWindow", "&Users"))
        self.actionUsers.setShortcut(_translate("MainWindow", "F5"))
        self.actionConnect.setText(_translate("MainWindow", "&Connect"))
        self.actionConnect.setShortcut(_translate("MainWindow", "F1"))
        self.actionLogin.setText(_translate("MainWindow", "&Login"))
        self.actionLogin.setShortcut(_translate("MainWindow", "F2"))
        self.actionClose_connection.setText(_translate("MainWindow", "Cl&ose connection"))
        self.actionClose_connection.setShortcut(_translate("MainWindow", "F4"))
        self.actionSend_mail.setText(_translate("MainWindow", "&Send mails"))
        self.actionPayments.setText(_translate("MainWindow", "&Payments"))
        self.actionLogs.setText(_translate("MainWindow", "&Logs"))
        self.actionOpen_log.setText(_translate("MainWindow", "&Open log"))
        self.actionOpen_log.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionBills.setText(_translate("MainWindow", "&Bills"))

