# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_bill.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.type = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type.sizePolicy().hasHeightForWidth())
        self.type.setSizePolicy(sizePolicy)
        self.type.setEditable(True)
        self.type.setObjectName("type")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.type)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.zlecenie = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zlecenie.sizePolicy().hasHeightForWidth())
        self.zlecenie.setSizePolicy(sizePolicy)
        self.zlecenie.setEditable(True)
        self.zlecenie.setObjectName("zlecenie")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zlecenie)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.platnik = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.platnik.sizePolicy().hasHeightForWidth())
        self.platnik.setSizePolicy(sizePolicy)
        self.platnik.setEditable(True)
        self.platnik.setObjectName("platnik")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.platnik)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.kwota = QtWidgets.QDoubleSpinBox(Dialog)
        self.kwota.setSuffix("")
        self.kwota.setMinimum(-1000000.0)
        self.kwota.setMaximum(10000000.0)
        self.kwota.setObjectName("kwota")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.kwota)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.liczba_godzin = QtWidgets.QDoubleSpinBox(Dialog)
        self.liczba_godzin.setMaximum(10000000.0)
        self.liczba_godzin.setObjectName("liczba_godzin")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.liczba_godzin)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.liczba_pomiarow = QtWidgets.QSpinBox(Dialog)
        self.liczba_pomiarow.setMaximum(100000000)
        self.liczba_pomiarow.setObjectName("liczba_pomiarow")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.liczba_pomiarow)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.od = QtWidgets.QDateEdit(Dialog)
        self.od.setObjectName("od")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.od)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.do_2 = QtWidgets.QDateEdit(Dialog)
        self.do_2.setObjectName("do_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.do_2)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.uwagi = QtWidgets.QLineEdit(Dialog)
        self.uwagi.setObjectName("uwagi")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.uwagi)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.id = QtWidgets.QLineEdit(Dialog)
        self.id.setEnabled(False)
        self.id.setObjectName("id")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.id)
        self.raport_line = QtWidgets.QLineEdit(Dialog)
        self.raport_line.setObjectName("raport_line")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.raport_line)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.status_line = QtWidgets.QLineEdit(Dialog)
        self.status_line.setObjectName("status_line")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.status_line)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nowy wpis"))
        self.label.setText(_translate("Dialog", "Dodaj nową pozycję"))
        self.label_2.setText(_translate("Dialog", "Rodzaj wpisu:"))
        self.label_3.setText(_translate("Dialog", "Rodzaj zlecenia:"))
        self.label_4.setText(_translate("Dialog", "Płatnik:"))
        self.label_5.setText(_translate("Dialog", "Kwota [PLN]:"))
        self.label_6.setText(_translate("Dialog", "Liczba godzin pomiarów:"))
        self.label_7.setText(_translate("Dialog", "Liczba pomiarów:"))
        self.label_8.setText(_translate("Dialog", "Za okres od:"))
        self.label_9.setText(_translate("Dialog", "do:"))
        self.label_10.setText(_translate("Dialog", "Uwagi:"))
        self.label_11.setText(_translate("Dialog", "Id:"))
        self.label_12.setText(_translate("Dialog", "Raport:"))
        self.label_13.setText(_translate("Dialog", "Status:"))

